### ISSUE TITLE
An error was reported while running toppic. Pressing "start" with the graphical user interface will flash back.

### ISSUE THREAD

**Issue by sunyusui** [toppic-suite/toppic-suite#1]
command line：

C:\Users\SYS\Documents\toppic-suite\bin>toppic human_proteome_database.fasta 
RP4H_P32_WHIM2_biorep1_techrep1_ms2.msalign > text2.log
Fatal parsing error at line0

C:\Users\SYS\Documents\toppic-suite\bin>topfd RP4H_P32_WHIM2_biorep1_techrep1.mzML
Fatal parsing error at line0

**Comment by sunyusui** [comment]
I am using a compiled executable, not an executable directly downloaded.

**Comment by liuxiaowen** [comment]
Please make sure that you link or copy the folder toppic_resource to the folder "toppic-suite\bin"

cd ../bin
ln -s ../toppic_resources .

**Comment by sunyusui** [comment]
My problem has been solved, thanks for your help.
