### ISSUE TITLE
Resource files are installed in /usr/etc

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#2]
Greetings, 

I am now packaging this software suite for Debian (I'm planning to use it in my own research on top-down proteomics). I discovered that the resources are installed in /usr/etc. The etc directory is for system configuration files. The FHS (filesystem hierarchy standard) states that the program architecture-independent resources (data, actually) should go in /usr/share. On most GNU/Linux systems (rpm- or deb-based alike), the resources/data are located in /usr/share/<package_name>. 

In my packaging of toppic-suite, I won't be able to keep the /usr/etc/ directory for the resources. I'll change that directory to /usr/share/toppic.  But, then I see that

./src/common/util/file_util.hpp has the path to <prefix>/etc hardcoded in it.

May I respectfully suggest that the directory in which data is installed be configured in the CMakeLists.txt file using the config file paradigm ? 

If you agree to such a configuration change, I could try to implement it (it is not going to be disruptive at all) and then send a merge request ?

Would you be ok for this ?

Yours, sincerely,
Filippo <lopippo@debian.org>

**Comment by lopippo** [comment]
Well, 

it seems even a bit more complicated, due to the fact that the paths to the resource dir are computed on the basis of the location of the executable being run:

`std::string getResourceDir(const std::string &exec_dir) {
// Edited for brevity
  std::string etc_dir = exec_dir + getFileSeparator() + getEtcDirName();
}
`
So, in the eventuality that the fixes are applied, that code could be replace using the <prefix>/usr/share/toppic directory configured in the CMakeLists.txt file ?

Or am I missing something, here ?

Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
Hi, Filippo,

Thank you for your suggestion. I am okay with it and please implement it.

Best,

Xiaowen

**Comment by liuxiaowen** [comment]
Hi, Filippo,

You can simply use the /usr/share/toppic directory to replace the code in getResourceDir. The function of getResourceDir is to find the directory of toppic_resources. In windows, the folder should be in the same folder of the binary file. We need to check both the folder of the binary file/toppic_resources and /usr/share/toppic.

Best,

Xiaowen

**Comment by lopippo** [comment]
Greetings, Xiaowen,

thank you very much for your kind answer. I'll definitely try to implement that in CMake with a configure_file command.

Yes, I did understand the difference between win and linux as to how the resources dir is found.

Sincerely,
Filippo

**Comment by lopippo** [comment]
Greetings, Fellow Developers,

I now have a Debian package that seems to be fine. I would like to test the software, now, with some mass data. Do you have some mass data files to use as tests and that are not confidential ? If so, could you please provide me with one or two such files so that I check that my build process is flawless ?
By the way, making such files available for users to learn the software might be a good idea _per se_.
Thanking you very much for your contribution to Free Software.
Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
Hi, Filippo,

Thank you for building the Debian package. You can find several test data sets at http://proteomics.informatics.iupui.edu/software/toppic/tutorial.html and a tutorial about using TopPIC for windows computers.

For the data in tutorial 1, you can download two top-down MS mzML data files at http://proteomics.informatics.iupui.edu/software/toppic/data_files/tutorial-1-mzml.zip and a protein sequence database at http://proteomics.informatics.iupui.edu/software/toppic/filedownload.php?filename=./data_files/uniprot-st.fasta

Best,

Xiaowen

**Comment by lopippo** [comment]
Thank you so much, I'll check all this soon.
