### ISSUE TITLE
Graphics format file does not match the file name

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#3]
Greetings,

please rename the following files:

topview/inspect/images/blue-download-icon-23.jpg
topview/inspect/images/download-icon-image-16.jpg 

that are actually PNG files.

Sincerely
Filippo

**Comment by liuxiaowen** [comment]
Filippo,

Thank you for pointing it out.

In Kwon – can you update the toppic repository at github.com to fix the problem?
https://github.com/toppic-suite/toppic-suite

Xiaowen

**Comment by 239cda** [comment]
issue fixed
