### ISSUE TITLE
JavaScript files are downloaded from the internet during execution

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#4]
Greetings,

here is another observation that I made while packaging toppic-suite: the JavaScript code downloads dynamically some files (fonts.css and datatables stuff) from the internet.
The Debian policy prohibits packaging code that downloads dynamically stuff from the internet. This is for obvious security and privacy reasons. 

The following hrefs are downloaded from the internet:

help.html [<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>] (https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css)

and 

help.html [<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js">] (https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js)

I looked at the cdn.datatables.net site and it seems that the license of these files is the MIT licence which make it possible to include these files directly in the source tree (see https://datatables.net/download/#dt/dt-1.10.18).

Would you mind making that transition to source-tree-stored files instead of dynamically downloaded files ? I would not be able to do that myself, as I'm not proficient enough in JavaScript develoment.

Sincerely,
Filippo Rusconi

**Comment by liuxiaowen** [comment]
In Kwon,

Can you fix the issue in the toppic repository at github.com?

Xiaowen
