### ISSUE TITLE
CMakeLists.txt line 12 does not work on GNU/Linux

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#4]
Greetings,

line 12: SET(CMAKE_INSTALL_PREFIX ${HOME}/toppic) resolves to /toppic on GNU/Linux. I guess the correct way to ask for env variables is $ENV{<variable>} as per https://cmake.org/cmake/help/latest/variable/ENV.html, which would yield:

SET(CMAKE_INSTALL_PREFIX $ENV{HOME}/toppic)

Sincerely,
Filippo

**Comment by lopippo** [comment]
No interest in this issue ?
Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
Filippo, We will fix the issue.

**Comment by liuxiaowen** [comment]
We will fix the issue.

**Comment by liuxiaowen** [comment]
Fixed in version 1.5.5

**Comment by liuxiaowen** [comment]
Hi, Filippo, 

We released version 1.5.5 and fixed the bugs you found in the new version. You can test the new version. 

Xiaowen

**Comment by lopippo** [comment]
Greetings, Xiaowen

> We released version 1.5.5 and fixed the bugs you found in the new version. You can test the new version.

Great, thank you, I'll go forward with the Debian package, then.
Sincerely,
Filippo
