### ISSUE TITLE
The _gui version of the binaries seems to not be installed

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#5]
Greetings,

in the CMakeLists.txt line referenced below
https://github.com/toppic-suite/toppic-suite/blob/8bb2623b93579247ca85f940539e90b45e5bcbce/CMakeLists.txt#L384

none of the _gui version of the binaries seems to be installed. Is this an oversight or is this intended ?

Sincerely,
Filippo

**Comment by lopippo** [comment]
Also, the topconvert binary is not installed neither.

Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
The Gui version and topconvert are not part of the released linux version of TopPIC.

**Comment by lopippo** [comment]
> The Gui version and topconvert are not part of the released linux version of TopPIC.

Ah, that's odd: they work perfectly well, as I have tested the first tutorial on Debian GNU/Linux and everything went flawlessly :-) Is there any reason these binaries are not for linux consumption ?
Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
There are still some bugs in the code. We will test them and add them to the released version.

**Comment by lopippo** [comment]
> There are still some bugs in the code. We will test them and add them to the released version.

Ah, now I understand. Thank you.
Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
We have fixed the bug and add the gui version to the installation in Linux in version 1.5.5.
