### ISSUE TITLE
Origin of toppic_resources/topview/visual/js/util/navBar.js

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#5]
Greetings,

I need to know where the navBar.js file comes from:

toppic_resources/topview/visual/js/util/navBar.js

In Debian, JavaScript files, if not authored by the authors of the package, need to be provided by their own package. I am thus trying to remove from the source tarball all the files that are available from official Debian packages and replacing them with symbolic links to the Debian packaged files. 
I could do that for a number of files, but not for navBar.js, that does not seem to be in any package in Debian.

Could you tell me from what source you got that file ?

Thank you very much for your attention
Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
Filippo,

We wrote the code of navbar.js, which is not a part of any other packages.

Best,

Xiaowen

**Comment by lopippo** [comment]
Greetings, Xiaowen
Ah, that is fine, then. Thank you very much,
sincerely,
Filippo
