### ISSUE TITLE
libfdeep dependency

### ISSUE THREAD

**Issue by lopippo** [toppic-suite/toppic-suite#7]
Greetings,

I am updating the toppic-suite project's Debian packaging and I see that it has evolved a lot. Congratulations for the new developments!

I would like to ask, since I am new to this aspect of the software: Are the Python scripts in libfdeep of use in your toppic-suite-based workflow, or are you only using the C++ header-only library?

I am currently trying to understand how to make the most of frugally-deep as a Debian package _per se_... I have already packaged libfplus and I would like to package libfdeep correctly.

Thank you for your attention and your insights,

Sincerely,
Filippo

**Comment by liuxiaowen** [comment]
Hi, Filippo, 

Thank you for working on the toppic-suite project! 

We use only the C++ header-only library of frugally-deep, not python scripts. Please let me know if you have other questions.  

Best,

Xiaowen

**Comment by lopippo** [comment]
Greetings, Xiaowen,

very fine, then. Thank you for your quick reply. I close this issue.
Sincerely,
Filippo
