### ISSUE TITLE
-DCMAKE_INSTALL_PREFIX overridden by CMakeLists

### ISSUE THREAD

**Issue by liv-acollins** [toppic-suite/toppic-suite#7]
Affects version 1.6.1

The cmake script is currently installing topic to /home/$USER/topic and ignoring the supplied install prefix. This prevents users from installing toppic to a shared location.

CMakeList.txt contains the following line:

`12 SET(CMAKE_INSTALL_PREFIX $ENV{HOME}/toppic)`

This line overrides using `-DCMAKE_INSTALL_PREFIX` when compiling the software:

`$ cmake -DCMAKE_INSTALL_PREFIX=/my/path/to/toppic ..`

Removing line 12 allows `-DCMAKE_INSTALL_PREFIX` to work as it should and Toppic can then be installed anywhere specified.

I'm not sure what the best practice for specifying a default is, but this is probably not it. Can you please remove/change this behaviour in future releases. ;)

**Comment by liuxiaowen** [comment]
Detritus, Thank you. We will fix the problem in future releases.

**Comment by liuxiaowen** [comment]
Hi, Detritus, 

We have fixed the issue in version 1.6.2.

Thank you. 

Xiaowen
