### ISSUE TITLE
Some questions in [deconv_data_util.cpp]

### ISSUE THREAD

**Issue by Xsakura1314** [toppic-suite/toppic-suite#8]
When I browse through the [**deconv_data_util.cpp**], I'm confused about the judgment of the max_charge and the max_mass.

![deconv_data_util.cpp](https://user-images.githubusercontent.com/59106419/114493277-d9c5d280-9c4c-11eb-90a2-c7b0da3c42e1.png)

The spec_max_charge & mass come from setData function in the [**deconv_process.cpp**], 30 and 100000,  are constant, but the para_max_charge & mass maybe affected by user settings

![deconv_process.cpp](https://user-images.githubusercontent.com/59106419/114493868-e8f95000-9c4d-11eb-91ba-2cc5a4752c70.png)

So judge a constant value has what effect？Why not judge a variable value？

And more, I found some duplicate chemical envelopes in the  [**theo_patt.txt**], won't this increase the number of judgments?

Expect to be able to answer my confusion.

**Comment by liuxiaowen** [comment]
The variable spec_max_mass is first set to the precursor mass and then is set to the minimum of the precursor mass and para_max_mass (user-defined). Some MS/MS spectra do not have precursor mass information. In this case, the spec_max_mass is first set to 100000 (default max mass) and then is set to the minimum of 100000 and para_max_mass.
